# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c4c1c599241812ef8e80d8c2b0fd1ba178bef737e02727056c01e4dcc26839cb0b07a0f3453771dd2dd877f29eb8b9d5b84ea109370052bcf5c6cfe7d97805b

test:
  secret_key_base: 91b09cc68478e2c13901ac1da444c76aeccdad8e170cb6c48d6c002c3467754074bc464568aed2c3cabc82b2310cb7dbbc437aaea3e67c97dca8186f5265a163

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
